[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "command-ai"
version = "0.0.4"
requires-python = ">=3.7"
dependencies = [
    "openai>=0.26",
]

[project.scripts]
ai = "ai.ai:main"
