[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "command-ai"
version = "0.1.0"
requires-python = ">=3.7"
dependencies = ["openai>=1.0"]

[project.scripts]
ai = "ai.ai:main"
